spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shiyi_comment
    username: postgres
    password: ******
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
server:
  port: 8083

logging:
  level:
    com.linshiyi.interaction: debug
    org.mybatis: debug
