spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shiyi_comment
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 600000

server:
  port: 8083

logging:
  level:
    com.linshiyi.interaction: info
    root: warn
  file:
    name: /var/log/interaction-service/logs.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30
