spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shiyi_article
    username: postgres
    password: ******
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
server:
  port: 8082

logging:
  level:
    com.linshiyi.article: debug
    org.mybatis: debug
