spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog_article?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: ******
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
server:
  port: 8082

logging:
  level:
    com.linshiyi.article: debug
    org.mybatis: debug
